apiVersion: v1
kind: Secret
metadata:
  name: jetdisc-secret
type: Opaque
data:
  DISCORD_APP_TOKEN: base64エンコードされたトークン
  BOT_NAME: base64エンコードされたボット名
  SET_COMMANDS_TARGET_SERVERS: base64エンコードされたサーバーID
  SPOTIFY_CLIENT_ID: base64エンコードされたSpotify Client ID
  SPOTIFY_CLIENT_SECRET: base64エンコードされたSpotify Client Secret
  SPOTIFY_AUTH_CALLBACK_URL: base64エンコードされたSpotify Auth Callback URL
