apiVersion: v1
kind: Secret
metadata:
  name: jetdisc-secret
type: Opaque
data:
  DISCORD_APP_TOKEN: base64エンコードされたトークン
  BOT_NAME: base64エンコードされたボット名
  SET_COMMANDS_TARGET_SERVERS: base64エンコードされたサーバーID
