replicaCount: 1

image:
  repository: na2na/jetdisc
  tag: "3.0.5"
  registry: docker.io
  pullPolicy: IfNotPresent

secrets:
  discordAppToken: ""

configMap:
  botName: ""
  storeDriver: "local"
  setCommandsTargetServers: ""

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

externalSecrets:
  enabled: true
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore
  targetName: jetdisc-secret
  creationPolicy: Owner
  refreshInterval: 1h
