replicaCount: 1

image:
  repository: na2na/jetdisc
  tag: "preview"
  pullPolicy: IfNotPresent

secret:
  name: jetdisc-secret
  DISCORD_APP_TOKEN: ""
  BOT_NAME: "2na2"
  SET_COMMANDS_TARGET_SERVERS: ""

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
