replicaCount: 1

image:
  repository: na2na/jetdisc
  tag: "3.0.5"
  registry: docker.io
  pullPolicy: IfNotPresent

secrets:
  discordAppToken: ""
  setCommandsTargetServers: ""

configMap:
  botName: ""
  storeDriver: "local"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
