apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jetdisc.fullname" . }}
  labels: {{- include "jetdisc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "jetdisc.name" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "jetdisc.name" . }}
        version: '{{ .Values.image.tag }}'
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.externalSecrets.targetName }}
            - configMapRef:
                name: jetdisc-configmap
          resources: {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
