{{ if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jetdisc-external-secret
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    namespace: {{  .Values.externalSecrets.secretStoreRef.namespace }}
  target:
    name: {{ .Values.externalSecrets.targetName }}
    creationPolicy: {{ .Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: DISCORD_APP_TOKEN
      remoteRef:
        key: jetdisc_discord_app_token
{{ end }}
