apiVersion: v1
kind: Secret
metadata:
  name: jetdisc-secret
type: Opaque
data:
  DISCORD_APP_TOKEN: {{ .Values.secrets.discordAppToken | b64enc | quote }}
  SET_COMMANDS_TARGET_SERVERS: {{ .Values.secrets.setCommandsTargetServers | b64enc }}
