apiVersion: v1
kind: Secret
metadata:
  name: jetdisc-secret
type: Opaque
data:
  DISCORD_APP_TOKEN: {{ .Values.secrets.discordAppToken }}
	SET_COMMANDS_TARGET_SERVERS: {{ .Values.secrets.setCommandsTargetServers | quote }}
