name: CD for PR
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3.0.2
        continue-on-error: true
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
      - name: asdf install
        uses: asdf-vm/actions/install@v3.0.2
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    needs: prepare
  image-build-for-ci:
    uses: ./.github/workflows/image-build.yml
    secrets: inherit
  image-scan:
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit
    needs: image-build-for-ci
    with:
      docker_image_tag_ci: ${{ needs.image-build-for-ci.outputs.docker_image_tag_ci }}
