name: CD for PR
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3.0.2
        continue-on-error: true
      - name: install ffmpeg dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm
      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
      - name: asdf install
        uses: asdf-vm/actions/install@v3.0.2
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    needs: prepare
