name: CD for main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3.0.2
        continue-on-error: true
      - name: install ffmpeg dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm
      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
      - name: asdf install
        uses: asdf-vm/actions/install@v3.0.2
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    needs: prepare
  image-build-for-ci:
    uses: ./.github/workflows/image-build.yml
    secrets: inherit
  image-scan:
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit
    needs: image-build-for-ci
    with:
      docker_image_tag_ci: ${{ needs.image-build-for-ci.outputs.docker_image_tag_ci }}
