name: CD for PR
on:
  pull_request:
    branches:
      - main
      - v3
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    needs: prepare
