name: CI
on: workflow_call

jobs:
  Build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3.0.2
        continue-on-error: true
      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
      - name: asdf install
        uses: asdf-vm/actions/install@v3.0.2
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build

  TypeCheck:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3.0.2
        continue-on-error: true
      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
      - name: asdf install
        uses: asdf-vm/actions/install@v3.0.2
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: typecheck
        run: pnpm tsc --noEmit

  Lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3.0.2
        continue-on-error: true
      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
      - name: asdf install
        uses: asdf-vm/actions/install@v3.0.2
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: fmt
        run: pnpm fmt
      - name: lint
        run: pnpm lint

  Test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Setup asdf
        uses: asdf-vm/actions/setup@v3.0.2
        continue-on-error: true
      - name: Cache asdf
        uses: actions/cache@v3
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
      - name: asdf install
        uses: asdf-vm/actions/install@v3.0.2
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: test
        run: pnpm test:coverage
        env:
          TZ: Asia/Tokyo
