name: Image Scan
on:
  workflow_call:
    inputs:
      docker_image_tag_ci:
        required: true
        type: string
    secrets: {}

env:
  COMPOSE_FILE: compose.ci.yml

jobs:
  build:
    name: Image Scan
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Docker Image
        uses: ./.github/actions/prepare-docker-image
        with:
          docker_image_tag_ci: ${{ inputs.DOCKER_IMAGE_TAG_CI }}
      - name: Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "localhost:5000/jetdisc-ci:${{ inputs.DOCKER_IMAGE_TAG_CI }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
